-- Create enum types for movies.genre
CREATE TYPE genre_type AS ENUM ('ACTION', 'ANIMATION', 'COMEDY', 'DRAMA', 'HISTORICAL', 'ROMANTIC', 'SOCIAL', 'SPORTS', 'THRILLER', 'WAR');

-- Create enum types for movies.language
CREATE TYPE language_type AS ENUM ('ENGLISH', 'HINDI', 'KANNADA', 'MARATHI', 'PUNJAB', 'TAMIL', 'TELUGU');

-- Create enum types for show_seats.seat_type and theater_seats.seat_type
CREATE TYPE seat_type AS ENUM ('CLASSIC', 'PREMIUM');

-- Create enum type for users.gender
CREATE TYPE gender_type AS ENUM ('FEMALE', 'MALE', 'OTHER');

-- Create movies table
CREATE TABLE movies (
    id INTEGER GENERATED BY DEFAULT AS IDENTITY,
    duration INTEGER,
    genre genre_type,
    language language_type,
    movie_name VARCHAR(255) NOT NULL,
    rating FLOAT,
    release_date DATE,
    PRIMARY KEY (id)
);

-- Create theaters table
CREATE TABLE theaters (
    id INTEGER GENERATED BY DEFAULT AS IDENTITY,
    address VARCHAR(255),
    name VARCHAR(255),
    PRIMARY KEY (id)
);

-- Create theater_seats table
CREATE TABLE theater_seats (
    id INTEGER GENERATED BY DEFAULT AS IDENTITY,
    seat_no VARCHAR(255),
    seat_type seat_type,
    theater_id INTEGER,
    PRIMARY KEY (id),
    FOREIGN KEY (theater_id) REFERENCES theaters(id)
);

-- Create shows table
CREATE TABLE shows (
    show_id INTEGER GENERATED BY DEFAULT AS IDENTITY,
    date DATE,
    time TIME(6),
    movie_id INTEGER,
    theater_id INTEGER,
    PRIMARY KEY (show_id),
    FOREIGN KEY (movie_id) REFERENCES movies(id),
    FOREIGN KEY (theater_id) REFERENCES theaters(id)
);

-- Create show_seats table
CREATE TABLE show_seats (
    id INTEGER GENERATED BY DEFAULT AS IDENTITY,
    is_available BOOLEAN,
    is_food_contains BOOLEAN,
    price INTEGER,
    seat_no VARCHAR(255),
    seat_type seat_type,
    show_show_id INTEGER,
    PRIMARY KEY (id),
    FOREIGN KEY (show_show_id) REFERENCES shows(show_id)
);

-- Create users table
CREATE TABLE users (
    id INTEGER GENERATED BY DEFAULT AS IDENTITY,
    address VARCHAR(255),
    age INTEGER,
    email_id VARCHAR(255),
    gender gender_type,
    mobile_no VARCHAR(255),
    name VARCHAR(255) NOT NULL,
    password VARCHAR(255),
    roles VARCHAR(255),
    PRIMARY KEY (id)
);

-- Create tickets table
CREATE TABLE tickets (
    ticket_id INTEGER GENERATED BY DEFAULT AS IDENTITY,
    booked_at DATE,
    booked_seats VARCHAR(255),
    total_tickets_price INTEGER,
    show_show_id INTEGER,
    user_id INTEGER,
    PRIMARY KEY (ticket_id),
    FOREIGN KEY (show_show_id) REFERENCES shows(show_id),
    FOREIGN KEY (user_id) REFERENCES users(id)
);